// <auto-generated />
using System;
using Archer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Archer.Migrations
{
    [DbContext(typeof(ArcherContext))]
    [Migration("20250303121634_Ijasz")]
    partial class Ijasz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Archer.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int?>("PlaygrounddId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentDay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaygrounddId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Archer.Models.Playgroundd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Playgroundd");
                });

            modelBuilder.Entity("Archer.Models.Booking", b =>
                {
                    b.HasOne("Archer.Models.Playgroundd", null)
                        .WithMany("Bookings")
                        .HasForeignKey("PlaygrounddId");
                });

            modelBuilder.Entity("Archer.Models.Playgroundd", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
